from __future__ import annotations

from collections.abc import AsyncIterator
from typing import Protocol

from playquick.models import PlaybackState, RepeatMode, Track


class PlaybackController(Protocol):
    @property
    def state(self) -> PlaybackState: ...

    async def start(self) -> None: ...
    async def close(self) -> None: ...
    async def play(self, track: Track) -> None: ...
    async def pause(self, paused: bool | None = None) -> None: ...
    async def stop(self) -> None: ...
    async def seek(self, seconds: float) -> None: ...
    async def set_volume(self, volume: int) -> None: ...
    async def next(self) -> None: ...
    async def previous(self) -> None: ...
    async def set_shuffle(self, enabled: bool) -> None: ...
    async def set_repeat(self, mode: RepeatMode) -> None: ...
    async def poll(self) -> PlaybackState: ...
    def states(self) -> AsyncIterator[PlaybackState]: ...

